import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  dashboardContainer: {
    flex: 1,
    backgroundColor: "#f8fafc",
  },
  adminHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 20,
    backgroundColor: "white",
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
    marginTop: 8,
  },
  adminHeaderText: {
    flex: 1,
  },
  adminName: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#1f2937",
    marginBottom: 4,
  },
  dateText: {
    fontSize: 13,
    color: "#9ca3af",
  },
  backButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: "#f3f4f6",
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  backIcon: {
    fontSize: 18,
    color: "#374151",
    fontWeight: "bold",
  },
  adminContent: {
    flex: 1,
  },
  statsOverview: {
    flexDirection: "row",
    padding: 16,
    gap: 12,
  },
  statCard: {
    flex: 1,
    padding: 20,
    borderRadius: 16,
    alignItems: "center",
    minHeight: 100,
    justifyContent: "center",
    elevation: 1,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
  },
  statNumber: {
    fontSize: 32,
    fontWeight: "800",
    color: "#0f172a",
    marginBottom: 6,
  },
  statLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: "#1e293b",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  tableContainer: {
    marginTop: 8,
    backgroundColor: "white",
    borderRadius: 16,
    overflow: "hidden",
    elevation: 1,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    borderWidth: 1,
    borderColor: "#f1f5f9",
    flex: 1,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#f8fafc",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
  },
  tableHeaderCell: {
    flex: 1,
    fontSize: 10,
    fontWeight: "700",
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  tableHeaderCellType: {
    flex: 0.6,
    fontSize: 10,
    fontWeight: "700",
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  tableHeaderCellStatus: {
    flex: 0.9,
    fontSize: 10,
    fontWeight: "700",
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  tableHeaderCellPriority: {
    flex: 0.8,
    fontSize: 10,
    fontWeight: "700",
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },

  tableBody: {
    flex: 1,
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
    backgroundColor: "#ffffff",
  },
  tableCell: {
    flex: 1.2,
    justifyContent: "center",
  },
  tableCellAdd: {
    flex: 1,
    justifyContent: "center",
    paddingRight: 16,
  },
  tableCellReq: {
    flex: 1.2,
    justifyContent: "center",
  },
  tableCellType: {
    flex: 0.9,
    justifyContent: "center",
  },
  tableCellStatus: {
    flex: 1.2,
    justifyContent: "center",
    paddingRight: 3,
  },
  tableCellPriority: {
    flex: 1,
    justifyContent: "center",
  },
  requestIdText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#0f172a",
    marginBottom: 2,
    paddingRight: 8,
  },
  unitText: {
    fontSize: 11,
    color: "#94a3b8",
    fontWeight: "500",
  },
  typeText: {
    fontSize: 12,
    color: "#334155",
    fontWeight: "600",
    paddingRight: 5,
    paddingLeft: 3,
  },
  addressText: {
    fontSize: 11,
    color: "#64748b",
    fontWeight: "400",
  },
  statusBadge2: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    fontSize: 9,
    fontWeight: "700",
    alignSelf: "flex-start",
    textAlign: "center",
    letterSpacing: 0.3,
  },
  bottomNav: {
    flexDirection: "row",
    backgroundColor: "white",
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    paddingVertical: 8,
    paddingHorizontal: 16,
    elevation: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  navButton: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 8,
    borderRadius: 8,
  },
  activeNavButton: {
    backgroundColor: "#eff6ff",
  },
  navIcon: {
    fontSize: 20,
    marginBottom: 4,
  },
  navText: {
    fontSize: 11,
    color: "#6b7280",
    fontWeight: "500",
  },
});

export default styles;
