import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  requestsModal: {
    backgroundColor: "white",
    borderRadius: 12,
    width: "90%",
    maxHeight: "80%",
    padding: 0,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#1f2937",
  },
  closeButton: {
    padding: 4,
  },
  closeButtonText: {
    fontSize: 28,
    color: "#6b7280",
    fontWeight: "300",
  },
  requestsList: {
    padding: 16,
  },
  requestModalCard: {
    backgroundColor: "#f9fafb",
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  clickableCard: {
    backgroundColor: "#ffffff",
  },
  requestModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 8,
  },
  requestModalId: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#1f2937",
  },
  requestModalBadges: {
    flexDirection: "row",
    gap: 6,
  },
  requestModalStatus: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 12,
    fontSize: 11,
    fontWeight: "600",
  },
  requestModalPriority: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 12,
    fontSize: 11,
    fontWeight: "600",
  },
  requestModalType: {
    fontSize: 13,
    fontWeight: "600",
    color: "#374151",
    marginBottom: 4,
  },
  requestModalDescription: {
    fontSize: 12,
    color: "#6b7280",
    marginBottom: 8,
  },
  requestModalFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  requestModalUnit: {
    fontSize: 12,
    color: "#374151",
    fontWeight: "500",
  },
  requestModalDate: {
    fontSize: 11,
    color: "#9ca3af",
  },
  technicianInfo: {
    flexDirection: "row",
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
  },
  technicianLabel: {
    fontSize: 11,
    color: "#6b7280",
  },
  technicianName: {
    fontSize: 11,
    color: "#2563eb",
    fontWeight: "600",
  },
  addressInfo: {
    flexDirection: "row",
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    alignItems: "center",
  },
  addressLabel: {
    fontSize: 12,
    color: "#6b7280",
  },
  addressText: {
    fontSize: 11,
    color: "#374151",
    fontWeight: "500",
    flex: 1,
  },
  detailModal: {
    backgroundColor: "white",
    borderRadius: 12,
    width: "90%",
    maxHeight: "85%",
    padding: 0,
  },
  detailContent: {
    padding: 16,
  },
  detailSection: {
    marginBottom: 16,
  },
  detailLabel: {
    fontSize: 12,
    color: "#6b7280",
    marginBottom: 4,
    fontWeight: "500",
  },
  detailValue: {
    fontSize: 15,
    color: "#1f2937",
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    fontSize: 13,
    fontWeight: "600",
    alignSelf: "flex-start",
  },
  priorityBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    fontSize: 13,
    fontWeight: "600",
    alignSelf: "flex-start",
  },
  prioritySelector: {
    flexDirection: "row",
    gap: 8,
    marginTop: 4,
  },
  priorityOption: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "#e5e7eb",
    alignItems: "center",
  },
  priorityOptionActive: {
    borderColor: "#374151",
    borderWidth: 2,
  },
  priorityOptionText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#6b7280",
  },
  actionButtons: {
    marginTop: 8,
    gap: 8,
  },
  actionButton: {
    padding: 14,
    borderRadius: 8,
    alignItems: "center",
  },
  assignButton: {
    backgroundColor: "#3b82f6",
  },
  completeButton: {
    backgroundColor: "#10b981",
  },
  cancelActionButton: {
    backgroundColor: "#6b7280",
  },
  actionButtonText: {
    color: "white",
    fontWeight: "600",
    fontSize: 14,
  },
  chatSection: {
    marginTop: 16,
    marginBottom: 16,
    backgroundColor: "#f9fafb",
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  chatSectionTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#374151",
    marginBottom: 12,
  },
  openChatButton: {
    backgroundColor: "#3b82f6",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: "center",
  },
  openChatButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "600",
  },
  chatContainer: {
    maxHeight: 250,
    marginBottom: 12,
  },
  chatMessage: {
    padding: 10,
    borderRadius: 8,
    marginBottom: 8,
    maxWidth: "85%",
  },
  chatMessageAdmin: {
    backgroundColor: "#dbeafe",
    alignSelf: "flex-end",
    borderBottomRightRadius: 2,
  },
  chatMessageHomeowner: {
    backgroundColor: "#ffffff",
    alignSelf: "flex-start",
    borderBottomLeftRadius: 2,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  chatSenderLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: "#6b7280",
    marginBottom: 4,
  },
  chatMessageText: {
    fontSize: 13,
    color: "#1f2937",
    marginBottom: 4,
  },
  chatMessageTime: {
    fontSize: 10,
    color: "#9ca3af",
    alignSelf: "flex-end",
  },
  noMessagesText: {
    fontSize: 13,
    color: "#9ca3af",
    textAlign: "center",
    paddingVertical: 20,
    fontStyle: "italic",
  },
  chatInputContainer: {
    flexDirection: "row",
    gap: 8,
    alignItems: "flex-end",
  },
  chatInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 8,
    padding: 10,
    paddingTop: 10,
    fontSize: 14,
    backgroundColor: "#ffffff",
    maxHeight: 80,
  },
  sendButton: {
    backgroundColor: "#3b82f6",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
    justifyContent: "center",
  },
  sendButtonText: {
    color: "white",
    fontWeight: "600",
    fontSize: 14,
  },
  assignModal: {
    backgroundColor: "white",
    borderRadius: 12,
    width: "90%",
    maxHeight: "70%",
    padding: 0,
  },
  assignContent: {
    padding: 16,
  },
  assignLabel: {
    fontSize: 14,
    color: "#374151",
    marginBottom: 8,
    fontWeight: "500",
  },
  textInput: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    marginBottom: 16,
    backgroundColor: "#f9fafb",
  },
  textArea: {
    height: 100,
    textAlignVertical: "top",
  },
  assignButtons: {
    flexDirection: "row",
    gap: 8,
    marginTop: 8,
  },
  confirmButton: {
    flex: 1,
    backgroundColor: "#3b82f6",
  },
  completeModal: {
    backgroundColor: "white",
    borderRadius: 12,
    width: "90%",
    maxHeight: "60%",
    padding: 0,
  },
  completeContent: {
    padding: 16,
  },
  completeLabel: {
    fontSize: 14,
    color: "#374151",
    marginBottom: 8,
    fontWeight: "500",
  },
  completeButtons: {
    flexDirection: "row",
    gap: 8,
    marginTop: 8,
  },
  confirmCompleteButton: {
    flex: 1,
    backgroundColor: "#10b981",
  },
});

export default styles;
