import { StyleSheet } from "react-native";
import { colors, spacing } from "../../../config/theme";

const styles = StyleSheet.create({
  pageHeader: {
    flexDirection: "row",
    alignItems: "center",
    padding: spacing.lg,
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.lg,
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    gap: spacing.lg,
    marginTop: 8,
  },
  backButton: {
    padding: spacing.sm,
  },
  backIcon: {
    fontSize: 24,
    color: colors.text.primary,
  },
  pageTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: colors.text.primary,
    flex: 1,
  },
  editButton: {
    backgroundColor: colors.accent,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 6,
  },
  editButtonText: {
    color: "white",
    fontWeight: "600",
    fontSize: 14,
  },
  cancelButton: {
    backgroundColor: "#6b7280",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 6,
  },
  cancelButtonText: {
    color: "white",
    fontWeight: "600",
    fontSize: 14,
  },
  profileContainer: {
    flex: 1,
    padding: spacing.xl,
    paddingHorizontal: 20,
    backgroundColor: colors.background,
  },
  profileAvatarSection: {
    alignItems: "center",
    marginBottom: spacing.xl,
    marginTop: 16,
  },
  avatarContainer: {
    position: "relative",
    alignItems: "center",
  },
  profileAvatarLarge: {
    width: 80,
    height: 80,
    borderRadius: 40,
    marginBottom: 12,
    borderWidth: 3,
    borderColor: colors.border,
  },
  editAvatarButton: {
    position: "absolute",
    bottom: 5,
    right: 5,
    backgroundColor: colors.accent,
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: colors.white,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  editAvatarIcon: {
    fontSize: 14,
    color: colors.white,
  },
  profileRole: {
    fontSize: 14,
    color: "#666",
    fontWeight: "500",
  },
  profileCard: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    marginBottom: spacing.xl,
  },
  profileField: {
    marginBottom: 20,
  },
  profileFieldLabel: {
    fontSize: 13,
    color: "#666",
    marginBottom: 6,
  },
  profileFieldValueContainer: {
    padding: 12,
    backgroundColor: "#f9fafb",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  profileFieldValue: {
    fontSize: 15,
    color: "#333",
    fontWeight: "500",
  },
  profileFieldInput: {
    padding: 12,
    backgroundColor: "#ffffff",
    borderRadius: 8,
    borderWidth: 2,
    borderColor: colors.accent,
    fontSize: 15,
    color: "#333",
    fontWeight: "500",
  },
  saveButton: {
    backgroundColor: "#10b981",
    padding: 14,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 8,
  },
  saveButtonText: {
    color: "white",
    fontWeight: "600",
    fontSize: 15,
  },
  logoutButton: {
    width: "100%",
    padding: 14,
    backgroundColor: colors.accent,
    borderRadius: 12,
    alignItems: "center",
    marginBottom: spacing.xxl,
  },
  logoutButtonText: {
    fontSize: 16,
    fontWeight: "bold",
    color: colors.white,
  },
});

export default styles;
